### ISSUE TITLE
头部检测问题

### ISSUE THREAD

**Issue by jun214384468** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#102]
如何用头部检测模型测试自己的图片呢？一直找不到

**Comment by jun214384468** [comment]
(yjh_torch) yan@whyhowinfo:~/yjh_work/LFFD/head_detection/accuracy_evaluation$ python predict.py 
Traceback (most recent call last):
  File "predict.py", line 264, in <module>
    run_prediction_pickle()
  File "predict.py", line 224, in run_prediction_pickle
    from config_farm import configuration_10_160_17L_4scales_v1 as cfg
ModuleNotFoundError: No module named 'config_farm'

**Comment by jun214384468** [comment]
就像这种的  为换成绝对路径from ..config_farm import configuration_10_160_17L_4scales_v1 as cfg也是不行

**Comment by jun214384468** [comment]
您好，没有测试但张图片的Demo吗

**Comment by yzl1014** [comment]
您的人脸和人头检测效果极差啊

**Comment by YonghaoHe** [comment]
@yzl1014 人脸是用WIDERFACE训练的，应该在大多数情况下是可以是用没问题的。人头的检测不能在其他场景是用，需要用自己的数据进行训练。

**Comment by lf2020** [comment]
@YonghaoHe @jun214384468  能否提供一个人头检测的ONNX模型，便于在其他框架中测试
