### ISSUE TITLE
TensorRT conversion failure

### ISSUE THREAD

**Issue by deimsdeutsch** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#27]
```
Traceback (most recent call last):
  File "to_onnx.py", line 38, in <module>
    generate_onnx_file()
  File "to_onnx.py", line 28, in generate_onnx_file
    onnx_mxnet.export_model(net_symbol, net_params, [input_shape], numpy.float32, onnx_path, verbose=True)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/contrib/onnx/mx2onnx/export_model.py", line 87, in export_model
    verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 309, in create_onnx_graph_proto
    checker.check_graph(graph)
  File "/usr/local/lib/python3.5/dist-packages/onnx/checker.py", line 52, in checker
    proto.SerializeToString(), ctx)
onnx.onnx_cpp2py_export.checker.ValidationError: Node (slice_axis20) has input size 1 not in range [min=3, max=5].

==> Context: Bad node spec: input: "softmax0" output: "slice_axis20" name: "slice_axis20" op_type: "Slice" attribute { name: "axes" ints: 1 type: INTS } attribute { name: "ends" ints: 1 type: INTS } attribute { name: "starts" ints: 0 type: INTS }

```

**Comment by YonghaoHe** [comment]
@deimsdeutsch I do not encounter this problem before. I think the mxnet version/onnx version matters.

**Comment by lucasjinreal** [comment]
@YonghaoHe  Same issue here:

```
mxnet-cu101                   1.5.1.post0            
```

onnx from the contrib of mxnet.

**Comment by YonghaoHe** [comment]
@jinfagang mxnet relies on external ONNX, which means you should install ONNX independently.

**Comment by gneworld** [comment]
same error  @YonghaoHe

**Comment by prnvjb** [comment]
Hey @YonghaoHe 
Could you share your mxnet and onnx versions?
Thanks!!

**Comment by smartwell** [comment]
@prnvjb @gneworld @jinfagang  i try onnx ==1.4  is OK.
