### ISSUE TITLE
pedestrian_detection训练时出错

### ISSUE THREAD

**Issue by codersabrinalee** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#48]
python configuration_30_320_20L_4scales_v1.py 训练网络出现错误，找了好久原因还是没有解决，主要有三个错误，
1是
Traceback (most recent call last):
File "/home/clb/env/lib/python3.5/site-packages/mxnet/symbol/symbol.py", line 1623, in simple_bind
ctypes.byref(exe_handle)))
File "/home/clb/env/lib/python3.5/site-packages/mxnet/base.py", line 253, in check_call
raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:27:07] src/storage/storage.cc:119: Compile with USE_CUDA=1 to enable GPU usage
Stack trace:

2是：
File "/home/clb/env/lib/python3.5/site-packages/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
shared_buffer=shared_data_arrays, **input_shapes)
File "/home/clb/env/lib/python3.5/site-packages/mxnet/symbol/symbol.py", line 1629, in simple_bind
raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:

3是
terminate called without an active exception
Aborted (core dumped)
能否指点一下解决方法 非常感谢

**Comment by YonghaoHe** [comment]
@codersabrinalee 你的mxnet版本有问题，没有GPU支持？
