### ISSUE TITLE
ValueError: could not broadcast input array from shape (1,3,368,368) into shape (1,3,250,250)

### ISSUE THREAD

**Issue by liuwenhua6666** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#79]
在运行predict_caffemodel_v2.py 报错：
----> Model is loaded successfully.
(368, 368, 3)
(1, 3, 368, 368)
Traceback (most recent call last):
  File "predict_caffemodel_v2.py", line 248, in <module>
    run_prediction_folder()
  File "predict_caffemodel_v2.py", line 235, in run_prediction_folder
    bboxes, _ = my_predictor.predict(im, resize_scale=1, score_threshold=0.9, top_k=10000, NMS_threshold=0.3, NMS_flag=True, skip_scale_branch_list=[])
  File "predict_caffemodel_v2.py", line 133, in predict
    self.net.blobs['data'].data[...] = input_image
ValueError: could not broadcast input array from shape (1,3,368,368) into shape (1,3,250,250)

**Comment by pedromoraesh** [comment]
did you find a solution?
